### ISSUE TITLE
Solution not working for me

### ISSUE THREAD

**Issue by JohnPettigrew** [macavon/action_text_style#2]
I need the ability to add styled text beyond what Trix allows by default so I was excited to see your solution here. Installing this test app locally shows it doing what it should, with colours saved and persisting across editing sessions.
However, when I replicate your solution in my own app (Rails 6.0.1, Trix 1.2.1), I don't get the desired result: the style is still stripped from the spans before the content is saved. The style string is present in the params before save, but when I check @model.content.body.to_s after the save, it's gone. 
I've copied the Trix config to add the new button into my app.js, and added the lines to config/application.rb. But it's not working for me.  :-(
Any ideas if there've been changes in the Trix or Rails source since you posted your solution that breaks it?

**Comment by macavon** [comment]
I'm terribly sorry not to have replied to your issue sooner – I didn't get a notification and only just saw the issue. Please accept my apologies.

I can tell you that my own application now running Rails 6.0.3 with Trix 1.2.0 is still working with coloured text. Like all developers say, 'It works for me'.

If you are still interested in this and still having problems, please let  me know and I'll see if I can help track it down.

**Comment by JohnPettigrew** [comment]
Thanks for the update. In the end, I dropped Twix and used a different lightweight editor with more control over the data. Twix/ActiveText looks great for knocking up a quick text-entry field, but no more than that IMO. It appears specifically designed to prevent customisation, and is almost completely undocumented. 🤷‍♂️
